### ISSUE TITLE
Formatting based on style guides

### ISSUE THREAD

**Issue by ferventcoder** [atom/language-puppet#10]
I don't see that this does this, but if it does feel free to close this. Would be nice to have a key combo that would automatically format the manifest.

**Comment by jacobbednarz** [comment]
I don't see why this wouldn't be possible but there would need to be a lot of smarts built in. Example, while single quotes is recommended you would need to ensure you don't change double quotes to single quotes if the string is interpolated with a variable.

I personally use [rodjek/puppet-lint](https://github.com/rodjek/puppet-lint) so perhaps we could leverage that here?

**Comment by ferventcoder** [comment]
Yes, definitely leverage existing tools.

**Comment by 50Wliu** [comment]
Atom's language packages are meant to only provide language highlighting - I would recommend installing a different package for formatting and linting.
