### ISSUE TITLE
Indents of => are not aligned

### ISSUE THREAD

**Issue by fazlearefin** [atom/language-puppet#15]
=> are not automatically aligned. 

This is what I get in atom:

``` puppet
class myssh {
  file { 'ssh_config.conf':
    ensure => file,
    mode => '0644',
    owner => 'root',
    ensure => 'file',
    target => '/etc/ssh/ssh_config',
  }
  # more code...
}
```

And this is what I am expecting (when typing a new => the alignment for all the => in that block should be adjusted so that they are all in one single column):

``` puppet
class myssh {
  file { 'ssh_config.conf':
    ensure => file,
    mode   => '0644',
    owner  => 'root',
    ensure => 'file',
    target => '/etc/ssh/ssh_config',
  }
  # more code...
}
```

See https://docs.puppetlabs.com/guides/style_guide.html#arrow-alignment

**Comment by helenes-r7** [comment]
I'm also experiencing this issue. I see there was an attempt to fix this earlier this year, so I'm not sure if it's a misconfiguration on my end. I've only installed the Atom packages language-puppet and linter-puppet-lint.
