### ISSUE TITLE
EPP Files not highlighted

### ISSUE THREAD

**Issue by gjngeldenhuis** [atom/language-puppet#19]
EPP files which is the native Puppet templating language does not get any syntax highlighting.

**Comment by saqibnaveed** [comment]
I want to contribute to this issue. I am a beginner, please guide me

**Comment by 50Wliu** [comment]
@saqibnaveed Just add it after `pp` here: https://github.com/atom/language-puppet/blob/master/grammars/puppet.cson#L2

See https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L2 if you need another example.

**Comment by saqibnaveed** [comment]
@50Wliu Okay Thanks. Let me try

**Comment by saqibnaveed** [comment]
Also please tell me do I need to add syntax markers and other things, etc or just the file type

sorry for asking such trivial questions.

**Comment by 50Wliu** [comment]
Fixed by #35.
