### ISSUE TITLE
No support for types in parameter lists

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/language-puppet#37]
<img width="576" alt="screen shot 2016-08-04 at 11 27 54 am" src="https://cloud.githubusercontent.com/assets/379509/17387387/aedf3730-5a36-11e6-8b2e-2743ccec9fbe.png">

As per the above snippet. It would be nice to have:
1. Comments greyed out
2. Parameter types (`SemVer`) to have a different colour to the parameter default (perhaps the same colour as used by resource names)

**Comment by 50Wliu** [comment]
> 2. Parameter types (SemVer) to have a different colour to the parameter default (perhaps the same colour as used by resource names)

Please create a new issue for this.

**Comment by alexjurkiewicz** [comment]
I'm trying to implement this myself. I think I can do 80% of it...
