### ISSUE TITLE
Block comments doesn't ignore quotes.

### ISSUE THREAD

**Issue by sc-chad** [atom/language-puppet#46]
Example:

``` puppet
/**
someclass { 'somename':
    path     =>    '/etc/somepath/**/*/somefile.log',
}
**/
```

The darkening of the comment breaks on the `/**/*` part of the path.

**Comment by 50Wliu** [comment]
As far as I can see, this is because you're actually *ending* the comment there with the `**/`.  Are Puppet comments aware of quotes?

**Comment by lee-dohm** [comment]
Thank you for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-puppet/issues/46#issuecomment-243560804. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
