### ISSUE TITLE
Unable to start the Puppet language server.

### ISSUE THREAD

**Issue by hugendudel** [atom/language-puppet#57]
Error: spawn /opt/puppetlabs/puppet/bin/ruby ENOENT

--

Hi folks,

just want to let you know this issue - I simply symlinked my OS ruby.

kind regards,
Harm

**Comment by 50Wliu** [comment]
This is an issue whatever package you're using that provides the Puppet language server, not language-puppet which is only responsible for tokenization/syntax-highlighting.
